# Generated by Django 4.2.25 on 2025-11-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FComptet',
            fields=[
                ('ct_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ct_intitule', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'F_COMPTET',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FDocentete',
            fields=[
                ('cbMarq', models.AutoField(primary_key=True, serialize=False)),
                ('do_piece', models.CharField(max_length=50)),
                ('do_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('do_statut', models.IntegerField(blank=True, null=True)),
                ('do_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'F_DOCENTETE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FDOCLIGNE',
            fields=[
                ('do_piece', models.CharField(max_length=50)),
                ('cbMarq', models.AutoField(primary_key=True, serialize=False)),
                ('AR_Ref', models.CharField(max_length=100)),
                ('DL_DESIGN', models.CharField(max_length=255)),
                ('DL_QTE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DL_PrixUnitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DL_Frais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DL_MontantHT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DL_MontantTTC', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'F_DOCLIGNE',
                'managed': False,
            },
        ),
    ]
